extern const GeoLayout sa_area_1_geo[];
extern const GeoLayout sa_area_1[];
extern const Collision sa_area_1_collision[];
extern const MacroObject sa_area_1_macro_objs[];
extern const GeoLayout sa_area_2_geo[];
extern const GeoLayout sa_area_2[];
extern const Collision sa_area_2_collision[];
extern const MacroObject sa_area_2_macro_objs[];
extern const GeoLayout sa_area_3_geo[];
extern const GeoLayout sa_area_3[];
extern const Collision sa_area_3_collision[];
extern const MacroObject sa_area_3_macro_objs[];
extern Lights1 sa_dl_bsfloor_001_lights;
extern Lights1 sa_dl_bsfloor_lights;
extern Lights1 sa_dl_psfloor_lights;
extern Vtx sa_dl_Plane_002_mesh_layer_1_vtx_0[4];
extern Gfx sa_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx sa_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx sa_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx sa_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx sa_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_sa_dl_bsfloor_001[];
extern Gfx mat_sa_dl_bsfloor[];
extern Gfx mat_sa_dl_psfloor[];
extern Gfx sa_dl_Plane_002_mesh_layer_1[];
extern Gfx sa_dl_Plane_001_mesh_layer_1[];
extern Gfx sa_dl_Plane_mesh_layer_1[];
extern Gfx sa_dl_material_revert_render_settings[];
