extern const GeoLayout sa_area_1_geo[];
extern const GeoLayout sa_area_1[];
extern const Collision sa_area_1_collision[];
extern const MacroObject sa_area_1_macro_objs[];
extern const GeoLayout sa_area_2_geo[];
extern const GeoLayout sa_area_2[];
extern const Collision sa_area_2_collision[];
extern const MacroObject sa_area_2_macro_objs[];
extern const GeoLayout sa_area_3_geo[];
extern const GeoLayout sa_area_3[];
extern const Collision sa_area_3_collision[];
extern const MacroObject sa_area_3_macro_objs[];
extern Lights1 sa_dl_green_lights;
extern Lights1 sa_dl_blue_lights;
extern Lights1 sa_dl_pink_lights;
extern Vtx sa_dl_Cube_mesh_vtx_0[24];
extern Gfx sa_dl_Cube_mesh_tri_0[];
extern Vtx sa_dl_Cube2_mesh_vtx_0[24];
extern Gfx sa_dl_Cube2_mesh_tri_0[];
extern Vtx sa_dl_Cube3_mesh_vtx_0[24];
extern Gfx sa_dl_Cube3_mesh_tri_0[];
extern Gfx mat_sa_dl_green[];
extern Gfx mat_sa_dl_blue[];
extern Gfx mat_sa_dl_pink[];
extern Gfx sa_dl_Cube_mesh[];
extern Gfx sa_dl_Cube2_mesh[];
extern Gfx sa_dl_Cube3_mesh[];
extern Gfx sa_dl_material_revert_render_settings[];
