extern const GeoLayout sa_area_2_geo[];
extern const GeoLayout sa_area_2[];
extern const Collision sa_area_2_collision[];
extern const MacroObject sa_area_2_macro_objs[];
extern const GeoLayout sa_area_1_geo[];
extern const GeoLayout sa_area_1[];
extern const Collision sa_area_1_collision[];
extern const MacroObject sa_area_1_macro_objs[];
extern Lights1 sa_dl_sm64_material_lights;
extern Vtx sa_dl_Plane_001_mesh_vtx_0[4];
extern Gfx sa_dl_Plane_001_mesh_tri_0[];
extern Gfx mat_sa_dl_sm64_material[];
extern Gfx sa_dl_Plane_001_mesh[];
extern Gfx sa_dl_material_revert_render_settings[];
