#include "levels/totwc/texture_include.inc.c"
#include "levels/totwc/area_1/collision.inc.c"
#include "levels/totwc/area_1/macro.inc.c"
#include "levels/totwc/area_1/spline.inc.c"
#include "levels/totwc/model.inc.c"
