// 0x0E000B90
const GeoLayout hmc_geo_000B90[] = {
   GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
   GEO_OPEN_NODE(),
      GEO_ZBUFFER(0),
      GEO_OPEN_NODE(),
         GEO_NODE_ORTHO(100),
         GEO_OPEN_NODE(),
            GEO_BACKGROUND_COLOR(0x0001),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
      GEO_ZBUFFER(1),
      GEO_OPEN_NODE(),
         GEO_CAMERA_FRUSTUM_WITH_FUNC(45, 100, 12800, geo_camera_fov),
         GEO_OPEN_NODE(),
            GEO_CAMERA(16, 0, 2000, 6000, 0, 0, 0, geo_camera_main),
            GEO_OPEN_NODE(),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, hmc_seg7_dl_070078B0),
               GEO_LEVEL_DISPLAY_LIST(LAYER_ALPHA, hmc_seg7_dl_07007B50),
               GEO_LEVEL_DISPLAY_LIST(LAYER_TRANSPARENT, hmc_seg7_dl_070080E8),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, hmc_seg7_dl_070093F0),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, hmc_seg7_dl_0700E448),
               GEO_LEVEL_DISPLAY_LIST(LAYER_ALPHA, hmc_seg7_dl_0700EF00),
               GEO_LEVEL_DISPLAY_LIST(LAYER_TRANSPARENT, hmc_seg7_dl_0700F3E8),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, hmc_seg7_dl_0700FA40),
               GEO_LEVEL_DISPLAY_LIST(LAYER_TRANSPARENT, hmc_seg7_dl_0700FEF0),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE_DECAL, hmc_seg7_dl_07010070),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, hmc_seg7_dl_07013CA8),
               GEO_LEVEL_DISPLAY_LIST(LAYER_ALPHA, hmc_seg7_dl_07013E80),
               GEO_LEVEL_DISPLAY_LIST(LAYER_TRANSPARENT, hmc_seg7_dl_07014300),
               GEO_LEVEL_DISPLAY_LIST(LAYER_TRANSPARENT, hmc_seg7_dl_07014B08),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, hmc_seg7_dl_07014C00),
               GEO_LEVEL_DISPLAY_LIST(LAYER_TRANSPARENT, hmc_seg7_dl_07014E48),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, hmc_seg7_dl_070173A8),
               GEO_LEVEL_DISPLAY_LIST(LAYER_ALPHA, hmc_seg7_dl_07017C98),
               GEO_LEVEL_DISPLAY_LIST(LAYER_TRANSPARENT, hmc_seg7_dl_07018200),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, hmc_seg7_dl_07019248),
               GEO_LEVEL_DISPLAY_LIST(LAYER_TRANSPARENT, hmc_seg7_dl_07019368),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, hmc_seg7_dl_0701A080),
               GEO_LEVEL_DISPLAY_LIST(LAYER_ALPHA, hmc_seg7_dl_0701A400),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, hmc_seg7_dl_0701E820),
               GEO_LEVEL_DISPLAY_LIST(LAYER_ALPHA, hmc_seg7_dl_0701F1B0),
               GEO_LEVEL_DISPLAY_LIST(LAYER_TRANSPARENT, hmc_seg7_dl_0701F690),
               GEO_LEVEL_DISPLAY_LIST(LAYER_TRANSPARENT, hmc_seg7_dl_0701F818),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, hmc_seg7_dl_0701FD58),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, hmc_seg7_dl_07020FD0),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, hmc_seg7_dl_07021760),
               GEO_LEVEL_DISPLAY_LIST(LAYER_TRANSPARENT, hmc_seg7_dl_07021BA0),
               GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, hmc_seg7_dl_070228A0),
               GEO_ASM(0, geo_painting_update),
               GEO_ASM(PAINTING_ID(0, 0), geo_painting_draw),
               GEO_ASM(0, geo_movtex_pause_control),
               GEO_ASM(0x0701, geo_movtex_draw_water_regions),
               GEO_ASM(0x0702, geo_movtex_draw_water_regions),
               GEO_RENDER_OBJ(),
               GEO_ASM(0, geo_envfx_main),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
