// 0x0E001560
const GeoLayout castle_geo_001560[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
   GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, inside_castle_seg7_dl_0703E6F0),
   GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, inside_castle_seg7_dl_07043028),
   GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, inside_castle_seg7_dl_07043B48),
   GEO_LEVEL_DISPLAY_LIST(LAYER_ALPHA, inside_castle_seg7_dl_07043CD8),
   GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, inside_castle_seg7_dl_0704A0E8),
   GEO_LEVEL_DISPLAY_LIST(LAYER_TRANSPARENT, inside_castle_seg7_dl_0704A2E0),
   GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, inside_castle_seg7_dl_0704AA98),
   GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, inside_castle_seg7_dl_0704C7D8),
   GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, inside_castle_seg7_dl_07050938),
   GEO_LEVEL_DISPLAY_LIST(LAYER_ALPHA, inside_castle_seg7_dl_07051678),
   GEO_LEVEL_DISPLAY_LIST(LAYER_TRANSPARENT, inside_castle_seg7_dl_070519C8),
   GEO_LEVEL_DISPLAY_LIST(LAYER_TRANSPARENT, inside_castle_seg7_dl_07051B60),
   GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, inside_castle_seg7_dl_070558D0),
   GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, inside_castle_seg7_dl_070572A0),
   GEO_LEVEL_DISPLAY_LIST(LAYER_OPAQUE, inside_castle_seg7_dl_07057F00),
   GEO_ASM(  0, geo_painting_update),
   GEO_ASM(PAINTING_ID(8, 1), geo_painting_draw),
   GEO_ASM(PAINTING_ID(9, 1), geo_painting_draw),
   GEO_ASM(PAINTING_ID(10, 1), geo_painting_draw),
   GEO_ASM(PAINTING_ID(11, 1), geo_painting_draw),
   GEO_ASM(PAINTING_ID(12, 1), geo_painting_draw),
   GEO_ASM(PAINTING_ID(13, 1), geo_painting_draw),
   GEO_ASM(  0, geo_render_mirror_mario),
   GEO_ASM(  0, geo_painting_update),
   GEO_CLOSE_NODE(),
   GEO_RETURN(),
};

// 0x0E001858
const GeoLayout castle_geo_001858[] = {
   GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
   GEO_OPEN_NODE(),
   GEO_ZBUFFER(0),
   GEO_OPEN_NODE(),
   GEO_NODE_ORTHO(100),
   GEO_OPEN_NODE(),
   GEO_BACKGROUND_COLOR(0x0001),
   GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_ZBUFFER(1),
   GEO_OPEN_NODE(),
   GEO_CAMERA_FRUSTUM_WITH_FUNC(64, 50, 8000, geo_camera_fov),
   GEO_OPEN_NODE(),
   GEO_CAMERA(4, 0, 2000, 6000, 0, 0, 0, geo_camera_main),
   GEO_OPEN_NODE(),
   GEO_BRANCH(1, castle_geo_001560),
   GEO_RENDER_OBJ(),
   GEO_ASM(0, geo_envfx_main),
   GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
