#include "levels/lll/texture_include.inc.c"
#include "levels/lll/area_1/collision.inc.c"
#include "levels/lll/area_1/macro.inc.c"
#include "levels/lll/area_1/spline.inc.c"
#include "levels/lll/model.inc.c"
